<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../src/Guardhouse.SDK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Guardhouse.SDK.Tests.cs" />
  </ItemGroup>

</Project>
